<?php

namespace Proxies\__CG__\BackEnd\Games\GamesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Jeu extends \BackEnd\Games\GamesBundle\Entity\Jeu implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'id', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'idJeu', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'nom', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'description', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'note', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'typeJeu', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'stock', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'plateformId', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'annee', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'etat', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'photo', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'prix');
        }

        return array('__isInitialized__', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'id', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'idJeu', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'nom', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'description', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'note', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'typeJeu', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'stock', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'plateformId', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'annee', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'etat', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'photo', '' . "\0" . 'BackEnd\\Games\\GamesBundle\\Entity\\Jeu' . "\0" . 'prix');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Jeu $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdJeu($idJeu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdJeu', array($idJeu));

        return parent::setIdJeu($idJeu);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdJeu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdJeu', array());

        return parent::getIdJeu();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote($note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', array($note));

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', array());

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeJeu($typeJeu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeJeu', array($typeJeu));

        return parent::setTypeJeu($typeJeu);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeJeu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeJeu', array());

        return parent::getTypeJeu();
    }

    /**
     * {@inheritDoc}
     */
    public function setStock($stock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStock', array($stock));

        return parent::setStock($stock);
    }

    /**
     * {@inheritDoc}
     */
    public function getStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStock', array());

        return parent::getStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlateformId($plateformId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlateformId', array($plateformId));

        return parent::setPlateformId($plateformId);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlateformId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlateformId', array());

        return parent::getPlateformId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnee($annee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnee', array($annee));

        return parent::setAnnee($annee);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnee', array());

        return parent::getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', array($etat));

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', array());

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', array($photo));

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', array());

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', array($prix));

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', array());

        return parent::getPrix();
    }

}
